"""
core/llm.py
------------
Interface to Groq Chat Completions API for RAG synthesis.
"""

import os
from typing import List, Dict, Any, Generator, Optional
from groq import Groq
import groq
from dotenv import load_dotenv
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type
from data_models import StructuredAnswer
from logs.logs_router import api_logger

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_MODEL = "llama-3.1-8b-instant"

if not GROQ_API_KEY:
    raise EnvironmentError("GROQ_API_KEY not found in environment.")

_client = Groq(api_key=GROQ_API_KEY)


@retry(
    stop=stop_after_attempt(5),
    wait=wait_exponential(multiplier=1, min=1, max=10),
    retry=retry_if_exception_type(groq.RateLimitError),
    reraise=True
)
def _client_chat_create_with_retry(*args, **kwargs):
    """
    Wrapper for Groq completion call with automatic tenacity-based retries.
    """
    model = kwargs.get("model", GROQ_MODEL)
    try:
        api_logger.info(f"Initiating Groq Chat Completion API Call - Model: {model}")
        res = _client.chat.completions.create(*args, **kwargs)
        api_logger.info(f"Groq Chat Completion API Call Success - Model: {model}")
        return res
    except groq.RateLimitError as rle:
        api_logger.warning(f"Groq API Rate Limit Hit! Detail: {rle}")
        raise
    except Exception as e:
        api_logger.error(f"Groq API Call Failed: {e}")
        raise


def generate_rag_stream(
    query: str,
    contexts: List[Dict[str, Any]]
) -> Generator[str, None, None]:
    """
    Generate a streamed answer synthesized from the retrieved contexts.

    Parameters
    ----------
    query : str
        The user's query.
    contexts : list[dict]
        Retrieved context chunks (each containing 'chunk_text', 'filename', 'page_no').

    Yields
    ------
    str
        Text tokens as they are generated by Groq.
    """
    # Construct context block
    context_str = ""
    for idx, c in enumerate(contexts, start=1):
        filename = c.get("filename", "Unknown file")
        page_no = c.get("page_no", "?")
        text = c.get("chunk_text", "")
        context_str += f"[{idx}] Source: {filename} (Page {page_no})\nContent: {text}\n\n"

    try:
        from helpers.prompt_loader import load_template
        template = load_template("rag_template.txt")
        system_prompt = template.format(rag_context=context_str, user_query=query)
    except Exception as e:
        print(f"Error loading rag_template.txt for streaming: {e}")
        system_prompt = (
            "You are HybridCache RAG v2's Assistant, an advanced AI designed to answer questions accurately "
            "using only the provided context retrieved from PDF documents.\n\n"
            "Instructions:\n"
            "1. Answer the question detail-by-detail, citing the sources in brackets (e.g. [1], [2]) "
            "whenever you use information from them.\n"
            "2. Keep your answers clear, professional, and well-structured. You can use markdown (bullet points, bold text).\n"
            "3. If the context does not contain enough information to answer the question, state politely "
            "that the context does not specify, but summarize any partial clues if present.\n"
            "4. Rely ONLY on the facts mentioned in the context. Do not make up or assume information."
        )

    user_content = f"CONTEXTS:\n{context_str}\n\nQUESTION: {query}"

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content}
    ]

    try:
        completion = _client_chat_create_with_retry(
            model=GROQ_MODEL,
            messages=messages,
            stream=True,
            temperature=0.2,
            max_tokens=1024,
        )
        for chunk in completion:
            token = chunk.choices[0].delta.content
            if token:
                yield token
    except Exception as e:
        print(f"Error during Groq generation: {e}")
        yield f"\n[Error generating answer: {e}]"


def generate_structured_answer(
    query: str,
    contexts: List[Dict[str, Any]],
    intent: str = "rag",
    chat_history: Optional[List[Dict[str, str]]] = None
) -> StructuredAnswer:
    """
    Generate a structured answer synthesized from the retrieved contexts.
    Uses Groq's JSON mode and parses the result with Pydantic model validation.
    """
    # Construct context block — also inject table markdown for pages that have tables
    import os
    from core.database import SessionLocal
    from schemas.table_schema import TableData

    context_str = ""
    injected_table_pages: set = set()  # avoid duplicate table injections

    for idx, c in enumerate(contexts, start=1):
        filename = c.get("filename", "Unknown file")
        page_no  = c.get("page_no", "?")
        text     = c.get("chunk_text", "")
        doc_id   = c.get("document_id")
        context_str += f"[{idx}] Source: {filename} (Page {page_no})\nContent: {text}\n\n"

        # Inject table markdown content for this page if not already done
        if c.get("has_tables") and doc_id and page_no and (doc_id, page_no) not in injected_table_pages:
            injected_table_pages.add((doc_id, page_no))
            db = SessionLocal()
            try:
                tbl_rows = db.query(TableData).filter(
                    TableData.document_id == doc_id,
                    TableData.page_no == page_no
                ).all()
                for tbl in tbl_rows:
                    tbl_path = tbl.table_path
                    if tbl_path and not os.path.isabs(tbl_path):
                        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
                        tbl_path = os.path.join(base_dir, tbl_path)
                    if tbl_path and os.path.exists(tbl_path):
                        with open(tbl_path, encoding="utf-8") as f:
                            tbl_md = f.read().strip()
                        tbl_header = tbl.header.lstrip('#').strip() if tbl.header else "Table"
                        context_str += (
                            f"Table on Page {page_no} (Section: {tbl_header}):\n"
                            f"{tbl_md}\n\n"
                        )
            except Exception as tbl_err:
                print(f"[LLM] Table injection warning: {tbl_err}")
            finally:
                db.close()

    # Dynamically retrieve the Pydantic model's JSON schema to instruct the LLM
    import json
    import re
    schema = StructuredAnswer.model_json_schema()
    schema_str = json.dumps(schema, indent=2)

    try:
        from helpers.prompt_loader import load_template
        if intent == "web_search":
            template = load_template("web_scrap.txt")
            web_results_str = ""
            for idx, r in enumerate(contexts, start=1):
                title = r.get("filename") or r.get("header") or "Web Page"
                url = r.get("source") or "No link"
                content = r.get("chunk_text") or ""
                web_results_str += f"[{idx}] Title: {title}\nURL: {url}\nContent: {content}\n\n"
            base_prompt = template.format(web_results=web_results_str, user_query=query)
            # Strip Response Format section from web_scrap.txt
            base_prompt_clean = re.sub(r'## Response Format.*?(?=## Quality Requirements|#|$)', '', base_prompt, flags=re.DOTALL)
        elif intent == "direct_llm":
            template = load_template("llm_template.txt")
            base_prompt = template
            # Strip Markdown Formatting section from llm_template.txt
            base_prompt_clean = re.sub(r'## Markdown Formatting.*?(?=## Response Adaptation|#|$)', '', base_prompt, flags=re.DOTALL)
        else: # rag
            template = load_template("rag_template.txt")
            base_prompt = template.format(rag_context=context_str, user_query=query)
            # Strip RESPONSE GUIDELINES and OUTPUT sections from rag_template.txt
            base_prompt_clean = re.sub(r'# RESPONSE GUIDELINES.*', '', base_prompt, flags=re.DOTALL)
    except Exception as e:
        print(f"Error loading template for intent {intent}: {e}. Falling back to default.")
        base_prompt_clean = (
            "You are HybridCache RAG v2's Assistant, an advanced AI designed to answer questions accurately "
            "using only the provided context retrieved from PDF documents."
        )

    system_prompt = (
        f"{base_prompt_clean}\n\n"
        "You must respond with a JSON object that strictly adheres to this JSON schema:\n"
        f"{schema_str}\n\n"
        "CRITICAL INSTRUCTIONS:\n"
        "1. Output ONLY a raw JSON object. Do NOT wrap the response in markdown code blocks (such as ```json). The output must start with '{' and end with '}'.\n"
        "2. Do NOT add any notes, conversational text, or explanations before or after the JSON block.\n"
        "3. Ensure the JSON is well-formed and matches the schema keys exactly ('answer', 'key_takeaways', 'suggested_followups').\n"
        "4. Keep explanations concise and relevant.\n"
        "5. For any tabular data, points tables, standings, statistical lists, or matrices, you MUST format the 'answer' text using standard Markdown pipe-table syntax (e.g., | Header 1 | Header 2 | followed by |---|---| on the next line). Do NOT output tabular data as lists, plain text, or preformatted text blocks."
    )

    user_content = f"CONTEXTS:\n{context_str}\n\nQUESTION: {query}" if intent != "direct_llm" else query

    messages = [{"role": "system", "content": system_prompt}]
    if chat_history:
        messages.extend(chat_history)
    messages.append({"role": "user", "content": user_content})

    # Try 1: Groq with response_format={"type": "json_object"}
    try:
        completion = _client_chat_create_with_retry(
            model=GROQ_MODEL,
            messages=messages,
            response_format={"type": "json_object"},
            temperature=0.2,
            max_tokens=1024,
        )
        raw_response = completion.choices[0].message.content
        return StructuredAnswer.model_validate_json(raw_response)
    except Exception as e:
        print(f"Groq JSON mode failed for structured generation: {e}. Retrying without JSON mode constraint...")
        
        # Try 2: Fallback without response_format and clean up markdown blocks in python
        try:
            completion = _client_chat_create_with_retry(
                model=GROQ_MODEL,
                messages=messages,
                temperature=0.2,
                max_tokens=1024,
            )
            raw_response = completion.choices[0].message.content
            
            # Helper to extract JSON from raw response
            cleaned_json = raw_response.strip()
            # Strip markdown wrappers if present
            if cleaned_json.startswith("```"):
                first_newline = cleaned_json.find("\n")
                if first_newline != -1:
                    cleaned_json = cleaned_json[first_newline:].strip()
                if cleaned_json.endswith("```"):
                    cleaned_json = cleaned_json[:-3].strip()
            
            start = cleaned_json.find("{")
            end = cleaned_json.rfind("}")
            if start != -1 and end != -1:
                cleaned_json = cleaned_json[start:end+1]
                
            return StructuredAnswer.model_validate_json(cleaned_json)
        except Exception as retry_e:
            print(f"Fallback structured generation failed: {retry_e}")
            return StructuredAnswer(
                answer=f"An error occurred while generating the structured answer: {e}",
                key_takeaways=["Error occurred during generation"],
                suggested_followups=["Try submitting your query again"]
            )


def generate_direct_answer(
    query: str,
    chat_history: Optional[List[Dict[str, str]]] = None
) -> StructuredAnswer:
    """
    Generate a general, direct answer to the query without retrieved contexts.
    Uses Groq's JSON mode and parses the result with Pydantic model validation.
    """
    import json
    import re
    schema = StructuredAnswer.model_json_schema()
    schema_str = json.dumps(schema, indent=2)

    try:
        from helpers.prompt_loader import load_template
        base_prompt = load_template("llm_template.txt")
    except Exception as e:
        print(f"Error loading llm_template.txt: {e}. Falling back to default.")
        base_prompt = "You are HybridCache RAG v2's Assistant, an advanced AI designed to answer questions accurately."

    # Strip markdown formatting examples from base_prompt to prevent model confusion in JSON mode
    base_prompt_clean = re.sub(r'## Markdown Formatting.*?(?=## Response Adaptation|#|$)', '', base_prompt, flags=re.DOTALL)

    system_prompt = (
        f"{base_prompt_clean}\n\n"
        "You must respond with a JSON object that strictly adheres to this JSON schema:\n"
        f"{schema_str}\n\n"
        "CRITICAL INSTRUCTIONS:\n"
        "1. Output ONLY a raw JSON object. Do NOT wrap the response in markdown code blocks (such as ```json). The output must start with '{' and end with '}'.\n"
        "2. Do NOT add any notes, conversational text, or explanations before or after the JSON block.\n"
        "3. Ensure the JSON is well-formed and matches the schema keys exactly ('answer', 'key_takeaways', 'suggested_followups').\n"
        "4. Provide a helpful, clear, and comprehensive answer to the user's question.\n"
        "5. Do not include or make up fake document citations since you are answering from general knowledge."
    )

    messages = [{"role": "system", "content": system_prompt}]
    if chat_history:
        messages.extend(chat_history)
    messages.append({"role": "user", "content": query})

    # Try 1: Groq with response_format={"type": "json_object"}
    try:
        completion = _client_chat_create_with_retry(
            model=GROQ_MODEL,
            messages=messages,
            response_format={"type": "json_object"},
            temperature=0.4,
            max_tokens=1024,
        )
        raw_response = completion.choices[0].message.content
        return StructuredAnswer.model_validate_json(raw_response)
    except Exception as e:
        print(f"Groq JSON mode failed for direct structured generation: {e}. Retrying without JSON mode constraint...")
        
        # Try 2: Fallback without response_format and clean up markdown blocks in python
        try:
            completion = _client_chat_create_with_retry(
                model=GROQ_MODEL,
                messages=messages,
                temperature=0.4,
                max_tokens=1024,
            )
            raw_response = completion.choices[0].message.content
            
            # Helper to extract JSON from raw response
            cleaned_json = raw_response.strip()
            # Strip markdown wrappers if present
            if cleaned_json.startswith("```"):
                first_newline = cleaned_json.find("\n")
                if first_newline != -1:
                    cleaned_json = cleaned_json[first_newline:].strip()
                if cleaned_json.endswith("```"):
                    cleaned_json = cleaned_json[:-3].strip()
            
            start = cleaned_json.find("{")
            end = cleaned_json.rfind("}")
            if start != -1 and end != -1:
                cleaned_json = cleaned_json[start:end+1]
                
            return StructuredAnswer.model_validate_json(cleaned_json)
        except Exception as retry_e:
            print(f"Fallback direct structured generation failed: {retry_e}")
            return StructuredAnswer(
                answer=f"An error occurred while generating the direct answer: {e}",
                key_takeaways=["Error occurred during direct generation"],
                suggested_followups=["Try submitting your query again"]
            )


